config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails-admin', as: 'rails_admin'

  authenticate :user, ->(u) { u.admin? } do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end

  get 'collections/create'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "dashboard", to: "dashboards#dashboard"
  get "unsubscribe", to: "dashboards#unsubscribe"
  get "subscribe", to: "dashboards#subscribe"
  post "cart_order", to: "carts#cart_order"
  post "single_tracks_cart", to: "carts#single_tracks"
  get "cart", to: "carts#cart"
  post "remove_item", to: "carts#delete_item"
  get "remove_track", to: "carts#delete_track"
  post "single_tracks_cart_remove", to: "carts#single_tracks_cart_remove"
  post "checkout", to: "orders#checkout"
  get "destroy_order", to: "orders#destroy"
  get "update_order_status", to: "orders#update_order_status"
  get "destroy_order_dashboard", to: "orders#destroy_from_dashboard"
  get "destroy_cart", to: "carts#destroy_cart"
  get "about", to: "pages#about"
  get "eula", to: "pages#eula"
  get "blog", to: "pages#blog"
  get "the_quest", to: "pages#the_quest"
  post "subscribe_no_user", to: "pages#subscribe"
  resources :sfx_packs, only: [:show, :index]

  resources :sound_designers, only: [:new, :create, :show] do
    resources :sfx_packs, only: [:create, :update]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  resources :sales, only: [:new, :create, :destroy]

  get 'list', to: 'single_tracks#index'
  get 'download_single', to: 'single_tracks#download_single'
  get 'create_zip', to: 'single_tracks#create_zip'
  get 'create_zip_collection', to: 'collections#create_zip_collection'

  resources :collections, only: [:create, :update, :show]
  post "name_update", to: "collections#name_update"
  post "convert", to: "collections#convert"
  post "remove_collection_from_cart", to: "collections#remove_collection_from_cart"
  delete "destroy_collection", to: "collections#destroy_collection"

  # create collection template --> admin
  post "create_collection_template", to: "collections#create_template"
  get "collection_templates", to: "collections#templates_index"
  get "collection_templates/:id", to: "collections#templates_show", as: :collection_template

  # user add template to cart and convert into collection
  get "add_template_to_cart", to: "collections#add_template_to_cart"

  # Sound Designer Submission
  resources :designer_submissions, param: :access_token, only: %i(new create show update) do
    resources :submission_links, only: :create
  end

  resources :designer_submissions, only: :destroy
  resources :submission_links, only: :destroy

  # thank you for your submission
  get "thank_you", to: "designer_submissions#thank_you", as: :thank_you

  # admin routes
  get "admin", to: "administrator#admin"
  get "admin/designer_submissions", to: "administrator#designer_submissions", as: :submissions
  get "admin/designer_legal_entities", to: "administrator#designer_legal_entities", as: :legal_entities_submissions
  get "admin/pack_submissions", to: "administrator#pack_submissions", as: :pack_submissions
  get "admin/designers_list", to: "administrator#designers_list", as: :designers_list
  get "admin/designers_offline", to: "administrator#designers_offline_list", as: :designers_offline_list
  get "admin/designers_rejected", to: "administrator#designers_rejected_list", as: :designers_rejected_list
  get "admin/designers/:id/packs", to: "administrator#designer_packs", as: :designer_packs
  patch "submission_accepted/:id", to: "administrator#submission_accepted", as: :submission_accepted
  patch "submission_rejected/:id", to: "administrator#submission_rejected", as: :submission_rejected
  post "admin/resend_confirmation/:user_id", to: "administrator#resend_confirmation", as: :resend_confirmation
  patch "pack_accepted/:id", to: "administrator#pack_accepted", as: :sfx_pack_accepted
  patch "pack_rejected/:id", to: "administrator#pack_rejected", as: :sfx_pack_rejected
  get "admin/stats", to: "administrator#stats", as: :stats
  get "admin/sales", to: "administrator#sales", as: :list_sales
  get "admin/payouts", to: "administrator#payouts", as: :admin_payouts
  get "admin/agreements", to: "administrator#agreements", as: :admin_agreements
  get "calculate_exchange_rate", to: "administrator#calculate_exchange_rate", as: :calculate_exchange_rate
  get "admin/legal_entity/:id", to: "administrator#legal_entity", as: :legal_entity
  patch "admin/legal_entity_accept/:id", to: "administrator#legal_entity_accept", as: :legal_entity_accept
  patch "admin/legal_entity_reject/:id", to: "administrator#legal_entity_reject", as: :legal_entity_reject
  post "admin/reject_designer/:designer_id", to: "administrator#reject_designer", as: :reject_designer
  patch "admin/paypal_accept/:id", to: "administrator#paypal_accept", as: :paypal_accept
  patch "admin/paypal_reject/:id", to: "administrator#paypal_reject", as: :paypal_reject
  resources :payouts, only: [:new, :create]

  # sound designer dashboard routes
  get "designer_dashboard", to: "designer_dashboards#main", as: :designer_main_dashboard
  get "your_listings", to: "designer_dashboards#listings", as: :designer_listings
  get "sales", to: "designer_dashboards#sales", as: :designer_sales
  get "payouts", to: "designer_dashboards#payouts", as: :designer_payouts
  get "settings", to: "designer_dashboards#settings", as: :settings
  get "add_new_pack", to: "designer_dashboards#pack_form", as: :add_new_pack
  get "update_pack/:id", to: "designer_dashboards#update_pack_form", as: :update_pack
  delete "remove_pack/:id", to: "designer_dashboards#remove_pack", as: :remove_pack
  post "sound_designers/:id/paypal_account", to: "designer_dashboards#paypal_account", as: :paypal_account
  post "sound_designers/:id/update_info", to: "designer_dashboards#update_designer_info", as: :update_designer_info
  post "sound_designers/:id/update_bio", to: "designer_dashboards#update_designer_bio", as: :update_designer_bio
  post "sound_designers/:id/update_photo", to: "designer_dashboards#update_designer_photo", as: :update_designer_photo
  post "sound_designers/:id/banner", to: "designer_dashboards#banner", as: :designer_banner

  # legal entities
  resources :legal_entities, only: [:new, :create, :edit, :update]

  # agreements
  get "agreements/:key/:version", to: "agreements#show", as: :agreement
  delete "agreements/:key/:version", to: "agreements#destroy", as: :delete_agreement
  get "agreements/:key/:version/deactivate", to: "agreements#deactivate", as: :deactivate_agreement
  get "agreements/:key/:version/activate", to: "agreements#activate", as: :activate_agreement
  get "agreements/:key/:version/pdf", to: "agreements#pdf", as: :pdf_agreement
  get "sound_designers/:id/seller_agreement", to: "agreements#seller_agreement", as: :seller_agreement

  # agreement acceptances
  resources :sound_designers, only: [] do
    resources :agreement_acceptances, only: :create
  end

  # data protection path
  get "data_protection", to: "pages#data_protection"

  # modal close path
  get "modal_closed", to: "pages#modal_closed"

  # jobs routes
  delete "jobs/:job_id", to: "jobs#destroy", as: :job

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # post "/webhooks/stripe", to: "stripe_webhook#receive"
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!, except: [:templates_index, :templates_show]

  def create
    # this action is not only to create a collection from scratch but add tracks to collection
    user_collection = Collection.where("user_id = #{current_user.id} and purchased = false").last
    if !user_collection.nil?
      user_collection.tracks << params[:track].to_i
      user_collection.tracks = user_collection.tracks.uniq
      user_collection.total_points = points(user_collection.tracks)
      user_collection.price_cents = collection_categories(user_collection.total_points)
      user_collection.save
    else
      Collection.create(user_id: current_user.id, tracks: [params[:track].to_i], total_points: SingleTrack.find(params[:track].to_i).points, price_cents: 500)
    end
    if !current_user.cart.nil?
      cart = current_user.cart
      cart.sinlge_tracks.delete(params[:track].to_i)
      cart.save
    end
    cart_create_update
    redirect_to request.referer
  end

  def update
    # this action is to remove tracks from collection
    collection = Collection.find(params[:id].to_i)
    cart = Cart.where(user_id: current_user.id).last
    collection.tracks.delete(params[:track].to_i)
    collection.total_points = points(collection.tracks)
    collection.price_cents = collection_categories(collection.total_points)
    collection.save

    # re-adjust price if applies


    # destroy collection if doesn't contain tracks
    if collection.tracks == []
      cart_remove_collection(collection, cart)
      collection.destroy
    end

    # destroy cart if empty
    cart.destroy if cart.items == [] && cart.sinlge_tracks == [] && cart.collections == []
    redirect_to request.referer
  end

  def convert
    # this action is not only to create a collection from scratch but add tracks to collection
    user_collection = Collection.where("user_id = #{current_user.id} and purchased = false").last
    if !user_collection.nil?
      params[:tracks].each do |track|
        user_collection.tracks << track.to_i
        user_collection.tracks = user_collection.tracks.uniq
        user_collection.total_points = points(user_collection.tracks)
        user_collection.price_cents = collection_categories(user_collection.total_points)
      end
      user_collection.save
    else
      # track_points = params[:tracks].map { |track| track = SingleTrack.find(track).price}
      # sum_points = track_points.sum
      price = CollectionCategory.where("points > #{params[:points]}").first.price * 100
      Collection.create(user_id: current_user.id, tracks: params[:tracks], total_points: params[:points], price_cents: price)
    end
    # Deleting all the single tracks from user
    current_user.cart.sinlge_tracks = []
    current_user.cart.save!
    redirect_to request.referer
  end

  def remove_collection_from_cart
    # this action does 4 things:
    # 1- removes a track from collection
    # 2- removes collection from cart of collection is empty
    # 3- destroys collection if collection is empty
    # 4- destroys cart when collection is destroyed if no other items in cart
    collection = Collection.find(params[:collection])
    collection.tracks.delete(params[:track].to_i)
    if collection.tracks == []
      cart = Cart.where(user_id: current_user.id).first
      cart.collections = []
      if cart.items == [] && cart.collections = [] && cart.sinlge_tracks == []
        cart.destroy
      else
        cart.save
      end
      collection.destroy
    else
      collection.total_points = points(collection.tracks)
      collection.price_cents = collection_categories(collection.total_points)
      collection.save
    end
    redirect_to cart_path
  end

  def destroy_collection
    collection = Collection.find(params[:collection])
    cart = Cart.where(user_id: current_user.id).first
    if cart.items == [] && cart.sinlge_tracks == []
      cart.destroy
      collection.destroy
    else
      cart.collections = []
      cart.save
      collection.destroy
    end
    redirect_to cart_path
  end

  def name_update
    name = name_params["input-name"]
    collection = Collection.find(params[:collection])
    collection.title = name
    collection.save
  end

  # /note/👇 old way for zipping files, using asset folder for local storage
  # def create_zip_collection
  #   Aws.config.update({
  #     region: 'eu-central-1',
  #     access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  #     secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
  #   })
  #   s3 = Aws::S3::Resource.new
  #   bucket = s3.bucket('single-track-list')
  #   files = []
  #   collection = Collection.find(params[:collection]).title
  #   tracks = Collection.find(params[:collection]).tracks
  #   tracks.each do |track|
  #     name = SingleTrack.find(track).link.split('.com').last[1..-1]
  #     files << name
  #   end
  #   time = Time.now.to_i
  #   folder = "#{current_user.username}_#{collection}_#{time}"
  #   Dir.mkdir(Rails.root.join('app', 'assets', 'uploads', folder))
  #   files.each do |file_name|
  #     file_obj = bucket.object(file_name)
  #     file_obj.get(response_target: Rails.root.join('app', 'assets', 'uploads', folder, file_name.split('/').last))
  #   end
  #   require 'zip'
  #   require 'fileutils'
  #   Zip::File.open(Rails.root.join('app', 'assets', 'uploads', folder, "#{folder}.zip"), Zip::File::CREATE) do |zipfile|
  #     files.each do |file_name|
  #      # Add the file to the zip
  #       zipfile.add(file_name, File.join(Rails.root.join('app', 'assets', 'uploads', folder, file_name.split('/').last)))
  #     end
  #   end
  #   send_file Rails.root.join('app', 'assets', 'uploads', folder, "#{folder}.zip"), disposition: 'attachment'
  #   # redirect_to dashboard_path, notice: "Your pack was successfully downloaded"
  # end

  # /note/👇 new way for zipping files, using AWS S3 to stream. Problem files larger then 500mb crash on Heroku
  # require 'zip'
  # require 'stringio'
  # require 'open-uri'

  # def create_zip_collection
  #   collection = Collection.find(params[:collection])
  #   tracks = collection.tracks
  #   time = Time.now.to_i
  #   zip_filename = "#{current_user.username}_#{collection.title}_#{time}.zip"

  #   # Set up in-memory zip
  #   compressed_filestream = Zip::OutputStream.write_buffer do |zos|
  #     tracks.each do |track_id|
  #       track = SingleTrack.find(track_id)
  #       s3_key = track.link.split('.com').last[1..-1]
  #       filename = File.basename(s3_key)

  #       # Get the file stream from S3 (public or presigned)
  #       s3_url = "https://single-track-list.s3.eu-central-1.amazonaws.com/#{s3_key}"
  #       file_stream = URI.open(s3_url)

  #       # Add it to the zip stream
  #       zos.put_next_entry(filename)
  #       IO.copy_stream(file_stream, zos)
  #     end
  #   end

  #   compressed_filestream.rewind

  #   send_data compressed_filestream.read,
  #             filename: zip_filename,
  #             type: 'application/zip'
  # end

  # /note/👇 this approach creates the zipfile and stores it on AWS
  def create_zip_collection
    if params[:type] == "single_tracks"
      params_object = {order: params[:order], tracks: params[:tracks], type: params[:type]}
    else
      params_object = {order: params[:order], collection: params[:collection]}
    end
    ZipCollectionJob.perform_later(params_object, current_user.id)
    # ZipCollectionJob.perform_now(params_object, current_user.id)
    # Aws.config.update({
    #   region: 'eu-central-1',
    #   access_key_id: ENV['AWS_ACCESS_KEY_ID'],
    #   secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
    # })
    # time = Time.now.to_i
    # order = Order.find(params[:order])

    # if params[:type] == "single_tracks"
    #   collection_download = false
    #   tracks = params[:tracks]
    #   zip_filename = "#{current_user.username}_tracks_#{time}.zip"
    # else
    #   collection_download = true
    #   collection = Collection.find(params[:collection])
    #   tracks = collection.tracks
    #   zip_filename = "#{current_user.username}_#{collection.title}_#{time}.zip"
    # end

    # # Create a temp file on disk
    # tempfile = Tempfile.new([zip_filename, '.zip'], binmode: true)

    # Zip::OutputStream.open(tempfile) do |zos|
    #   tracks.each do |track_id|
    #     track = SingleTrack.find(track_id)
    #     s3_key = track.link.split('.com').last[1..-1]
    #     filename = File.basename(s3_key)

    #     # Stream from S3
    #     s3_url = "https://single-track-list.s3.eu-central-1.amazonaws.com/#{s3_key}"
    #     URI.open(s3_url) do |file_stream|
    #       zos.put_next_entry(filename)
    #       IO.copy_stream(file_stream, zos)
    #     end
    #   end
    # end

    # tempfile.rewind

    # # Upload to S3 using aws-sdk-s3
    # s3 = Aws::S3::Resource.new(region: 'eu-central-1')
    # obj = s3.bucket('bamsfx-temp-zip-files').object("zips/#{zip_filename}")
    # obj.upload_file(tempfile.path, acl: 'private')

    # # Generate a presigned URL (expires in 1 day)
    # url = obj.presigned_url(:get, expires_in: 86400)

    # # Clean up temp file
    # tempfile.close
    # tempfile.unlink

    # # create a download_link and redirect
    # if collection_download
    #   DownloadLink.create(url: url, collection: collection, collection_download: true, order: order, validity_duration: Time.at(1.hour))
    # else
    #   DownloadLink.create(url: url, collection_download: false, order: order, validity_duration: Time.at(1.hour))
    # end
    # # Return the URL to the user (e.g., as JSON)
    # # render json: { download_url: url }
    redirect_to dashboard_path
  end

  def create_template
    collection = Collection.find(params[:template][:collection])
    title = params[:template][:title]
    categories = params[:template][:categories].split(", " || "")

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/create.html.erb
<h1>Collections#create</h1>
<p>Find me in app/views/collections/create.html.erb</p>

app/views/collections/templates_index.html.erb
<div class="content">
  <div class="banner">
    <h1 class="padding-navbar font-permanent-marker">Build your own Sound Pack!!!</h1>
    <button class="learn-more learnMoreBtn">Learn more</button>
  </div>
  <%= render "shared/left_pannel_mobile"%>
  <!-- Desktop display -->
  <div class="template-display-desktop">
    <div class="d-flex">
      <%= render "shared/left_pannel_desktop"%>
      <div class="template-section text-center" data-controller="unwrap-cart">
        <div class="template-info-banner d-flex justify-content-center">
          <div><%= image_tag("sword.png", height: "40px") %></div>&nbsp;&nbsp;
          <h4>Chose a template bellow, customize it, and create the perfect SFX Pack for your projects!!!</h4>&nbsp;&nbsp;
          <div><%= image_tag("sword.png", height: "40px") %></div>
        </div>
        <% if !@templates.empty? %>
        <!--
          <div class="template-section-grid">
            <% @templates.order(created_at: :desc).each do |template| %>
              <%# render 'shared/templates/templates_display', collection: template %>
              <%= render 'shared/collection_card', collection: template %>
            <% end %>
          </div>
        -->
          <div class="">
            <%= render 'shared/collection_card' %>
          </div>
        <% else %>
          <h3>No collections at this time</h3>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- The Learn More Modal -->
<div id="learnMore" class="learn-more-modal">
  <!-- Modal content -->
  <div class="learn-more-modal-content">
    <span class="learn-more-close">&times;</span>
    <div class="d-flex justify-content-center">
      <div>
        <%= image_tag asset_path('knight.png'), id: "knight-gif" %>
      </div>
      <div>
        <h2 id="comming-soon">Create your Collection!!!</h2>
      </div>
    </div>
    <%# <br>
    <h5><span class="orange-words">Collections</span> are a very cool feature that lets you
    create your own <span class="orange-words">Sound Effects Pack</span>.</h5>
    <p>You might need a very specific set of sounds for your film or video game. You might not want to pay for 3 different packs or
    buy the tracks separately which can become pretty expensive!</p>
    <br><h3 style="text-align: center">Introducing the <span class="orange-words">Collection System</span></h3> %>
    <br><h5><%= image_tag asset_path('sword.png'), id: "sword-gif" %>Select your tracks buy clicking on the <i class="fas fa-box-open orange-words"></i> icon.
    <br><%= image_tag asset_path('sword.png'), id: "sword-gif" %>Each track is attributed some points <span id="point-explanation-modal">&nbsp1&nbsp</span> which are added up to determine your very attractive collection price!
    <br><%= image_tag asset_path('sword.png'), id: "sword-gif" %>You can get up to <span class="orange-words">20</span> tracks for just <span class="orange-words">$5</span> check it out!!!</h5><br>
    <%= image_tag asset_path('collection.png'), id: "collection-image" %>
  </div>
</div>

app/views/collections/templates_show.html.erb
<% content_for :meta_title, @template_collection.title %>
<% content_for :meta_description, "Create your own SFX packs with the collection system! Custom made packs at an unbeatable price!!!" %>
<% content_for :meta_image, @template_collection.image.attached? ? url_for(@template_collection.image) : image_url("https://res.cloudinary.com/dk9a86uhu/image/upload/v1695194012/sfx_shop/BamSFX_meta_vcgic4.png") %>
<% if session[:currency] != "$" %>
  <% conversion_rate = CurrencyRate.where("base = ? AND target = ?", "USD", "EUR").order(created_at: :desc).first.rate.to_f %>
<% else %>
  <% conversion_rate = 1 %>
<% end %>
<div class="content">
  <div class="banner">
    <h1 class="padding-navbar"><%= @template_collection.title %> Collection!</h1>
    <button class="learn-more learnMoreBtn">Learn more</button>
  </div>
  <%= render "shared/left_pannel_mobile"%>
  <div class="d-flex">
    <%= render "shared/left_pannel_desktop"%>
    <div class="container-fluid" style="position: relative">
      <% if (@template_collection.created_at.year - 2022) < 2 %>
        <%= image_tag asset_path("New_orange_transp_small.png"), style: "position: absolute; height: 62px; top: 0px; left: 0px; transform: rotate(-60deg)" %>
      <% end %>
      <div class="d-flex justify-content-between collection-title-banner">
        <div class="d-flex">
          <i class="<%= @icons[@template_collection.categories.first.to_sym].split('"')[1] %> template-icon-adjust"></i>
          <div class="d-flex flex-column">
            <div class="d-flex">
              <h3 class="template-title"> <strong><%= @template_collection.title %> Collection</strong> </h3>
            </div>
            <div class="template-price-desktop">
              <div class="d-flex">
                <h5><%= humanized_money(@template_collection.price * conversion_rate, symbol: session[:currency]) %></h5><span class="template-track-count">/</span><h5><%= @template_collection.tracks.count %> tracks</h5>
              </div>
            </div>
          </div>
        </div>
        <div class="template-price-mobile">
          <div class="d-flex">
            <h5><%= humanized_money(@template_collection.price * conversion_rate, symbol: session[:currency]) %></h5><span class="template-track-count">/</span><h5><%= @template_collection.tracks.count %> tracks</h5>
          </div>
        </div>
        <div id="add-button">
          <%= link_to 'Add to Cart', add_template_to_cart_path(template_id: @template_collection.id), id: 'btn-cart-show' %>
        </div>
      </div>
      <div id="" data-controller="filters">
        <%= render 'shared/paginate_tracks' %>
      </div>
      <%# MOBILE %>
      <div id="paginate-mobile" class="screen-display">
        <% render 'shared/paginate_tracks' %>
      </div>

    </div>
  </div>
</div>

<!-- The Learn More Modal -->
<div id="learnMore" class="learn-more-modal">
  <!-- Modal content -->
  <div class="learn-more-modal-content">
    <span class="learn-more-close">&times;</span>
    <div class="d-flex justify-content-center">
      <div>
        <%= image_tag asset_path('knight.png'), id: "knight-gif" %>
      </div>
      <div>
        <h2 id="comming-soon">Build your own Sound Pack!!!</h2>
      </div>
    </div>
    <%# <br>
    <h5><span class="orange-words">Collections</span> are a very cool feature that lets you
    create your own <span class="orange-words">Sound Effects Pack</span>.</h5>
    <p>You might need a very specific set of sounds for your film or video game. You might not want to pay for 3 different packs or
    buy the tracks separately which can become pretty expensive!</p>
    <br><h3 style="text-align: center">Introducing the <span class="orange-words">Collection System</span></h3> %>
    <br><h5><%= image_tag asset_path('sword.png'), id: "sword-gif" %>Select your tracks buy clicking on the <i class="fas fa-box-open orange-words"></i> icon.
    <br><%= image_tag asset_path('sword.png'), id: "sword-gif" %>Each track is attributed some points <span id="point-explanation-modal">&nbsp1&nbsp</span> which are added up to determine your very attractive collection price!
    <br><%= image_tag asset_path('sword.png'), id: "sword-gif" %>You can get up to <span class="orange-words">20</span> tracks for just <span class="orange-words">$5</span> check it out!!!</h5><br>
    <%= image_tag asset_path('collection.png'), id: "collection-image" %>
  </div>
</div>