config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails-admin', as: 'rails_admin'

  authenticate :user, ->(u) { u.admin? } do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end

  get 'collections/create'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "dashboard", to: "dashboards#dashboard"
  get "unsubscribe", to: "dashboards#unsubscribe"
  get "subscribe", to: "dashboards#subscribe"
  post "cart_order", to: "carts#cart_order"
  post "single_tracks_cart", to: "carts#single_tracks"
  get "cart", to: "carts#cart"
  post "remove_item", to: "carts#delete_item"
  get "remove_track", to: "carts#delete_track"
  post "single_tracks_cart_remove", to: "carts#single_tracks_cart_remove"
  post "checkout", to: "orders#checkout"
  get "destroy_order", to: "orders#destroy"
  get "update_order_status", to: "orders#update_order_status"
  get "destroy_order_dashboard", to: "orders#destroy_from_dashboard"
  get "destroy_cart", to: "carts#destroy_cart"
  get "about", to: "pages#about"
  get "eula", to: "pages#eula"
  get "blog", to: "pages#blog"
  get "the_quest", to: "pages#the_quest"
  post "subscribe_no_user", to: "pages#subscribe"
  resources :sfx_packs, only: [:show, :index]

  resources :sound_designers, only: [:new, :create, :show] do
    resources :sfx_packs, only: [:create, :update]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  resources :sales, only: [:new, :create, :destroy]

  get 'list', to: 'single_tracks#index'
  get 'download_single', to: 'single_tracks#download_single'
  get 'create_zip', to: 'single_tracks#create_zip'
  get 'create_zip_collection', to: 'collections#create_zip_collection'

  resources :collections, only: [:create, :update, :show]
  post "name_update", to: "collections#name_update"
  post "convert", to: "collections#convert"
  post "remove_collection_from_cart", to: "collections#remove_collection_from_cart"
  delete "destroy_collection", to: "collections#destroy_collection"

  # create collection template --> admin
  post "create_collection_template", to: "collections#create_template"
  get "collection_templates", to: "collections#templates_index"
  get "collection_templates/:id", to: "collections#templates_show", as: :collection_template

  # user add template to cart and convert into collection
  get "add_template_to_cart", to: "collections#add_template_to_cart"

  # Sound Designer Submission
  resources :designer_submissions, param: :access_token, only: %i(new create show update) do
    resources :submission_links, only: :create
  end

  resources :designer_submissions, only: :destroy
  resources :submission_links, only: :destroy

  # thank you for your submission
  get "thank_you", to: "designer_submissions#thank_you", as: :thank_you

  # admin routes
  get "admin", to: "administrator#admin"
  get "admin/designer_submissions", to: "administrator#designer_submissions", as: :submissions
  get "admin/designer_legal_entities", to: "administrator#designer_legal_entities", as: :legal_entities_submissions
  get "admin/pack_submissions", to: "administrator#pack_submissions", as: :pack_submissions
  get "admin/designers_list", to: "administrator#designers_list", as: :designers_list
  get "admin/designers_offline", to: "administrator#designers_offline_list", as: :designers_offline_list
  get "admin/designers_rejected", to: "administrator#designers_rejected_list", as: :designers_rejected_list
  get "admin/designers/:id/packs", to: "administrator#designer_packs", as: :designer_packs
  patch "submission_accepted/:id", to: "administrator#submission_accepted", as: :submission_accepted
  patch "submission_rejected/:id", to: "administrator#submission_rejected", as: :submission_rejected
  post "admin/resend_confirmation/:user_id", to: "administrator#resend_confirmation", as: :resend_confirmation
  patch "pack_accepted/:id", to: "administrator#pack_accepted", as: :sfx_pack_accepted
  patch "pack_rejected/:id", to: "administrator#pack_rejected", as: :sfx_pack_rejected
  get "admin/stats", to: "administrator#stats", as: :stats
  get "admin/sales", to: "administrator#sales", as: :list_sales
  get "admin/payouts", to: "administrator#payouts", as: :admin_payouts
  get "admin/agreements", to: "administrator#agreements", as: :admin_agreements
  get "calculate_exchange_rate", to: "administrator#calculate_exchange_rate", as: :calculate_exchange_rate
  get "admin/legal_entity/:id", to: "administrator#legal_entity", as: :legal_entity
  patch "admin/legal_entity_accept/:id", to: "administrator#legal_entity_accept", as: :legal_entity_accept
  patch "admin/legal_entity_reject/:id", to: "administrator#legal_entity_reject", as: :legal_entity_reject
  post "admin/reject_designer/:designer_id", to: "administrator#reject_designer", as: :reject_designer
  patch "admin/paypal_accept/:id", to: "administrator#paypal_accept", as: :paypal_accept
  patch "admin/paypal_reject/:id", to: "administrator#paypal_reject", as: :paypal_reject
  resources :payouts, only: [:new, :create]

  # sound designer dashboard routes
  get "designer_dashboard", to: "designer_dashboards#main", as: :designer_main_dashboard
  get "your_listings", to: "designer_dashboards#listings", as: :designer_listings
  get "sales", to: "designer_dashboards#sales", as: :designer_sales
  get "payouts", to: "designer_dashboards#payouts", as: :designer_payouts
  get "settings", to: "designer_dashboards#settings", as: :settings
  get "add_new_pack", to: "designer_dashboards#pack_form", as: :add_new_pack
  get "update_pack/:id", to: "designer_dashboards#update_pack_form", as: :update_pack
  delete "remove_pack/:id", to: "designer_dashboards#remove_pack", as: :remove_pack
  post "sound_designers/:id/paypal_account", to: "designer_dashboards#paypal_account", as: :paypal_account
  post "sound_designers/:id/update_info", to: "designer_dashboards#update_designer_info", as: :update_designer_info
  post "sound_designers/:id/update_bio", to: "designer_dashboards#update_designer_bio", as: :update_designer_bio
  post "sound_designers/:id/update_photo", to: "designer_dashboards#update_designer_photo", as: :update_designer_photo
  post "sound_designers/:id/banner", to: "designer_dashboards#banner", as: :designer_banner

  # legal entities
  resources :legal_entities, only: [:new, :create, :edit, :update]

  # agreements
  get "agreements/:key/:version", to: "agreements#show", as: :agreement
  delete "agreements/:key/:version", to: "agreements#destroy", as: :delete_agreement
  get "agreements/:key/:version/deactivate", to: "agreements#deactivate", as: :deactivate_agreement
  get "agreements/:key/:version/activate", to: "agreements#activate", as: :activate_agreement
  get "agreements/:key/:version/pdf", to: "agreements#pdf", as: :pdf_agreement
  get "sound_designers/:id/seller_agreement", to: "agreements#seller_agreement", as: :seller_agreement

  # agreement acceptances
  resources :sound_designers, only: [] do
    resources :agreement_acceptances, only: :create
  end

  # data protection path
  get "data_protection", to: "pages#data_protection"

  # modal close path
  get "modal_closed", to: "pages#modal_closed"

  # jobs routes
  delete "jobs/:job_id", to: "jobs#destroy", as: :job

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # post "/webhooks/stripe", to: "stripe_webhook#receive"
end

app/views/shared/_collections_horizontal.html.erb
<% collections.order(created_at: :desc).first(6).each do |collection| %>
  <%= render "shared/collection_card", collection: collection %>
<% end %>

app/views/shared/_dashboard_collection_tracks.html.erb
<div data-controller="collection-checkout-modal">
  <div class="dashboard-collection-grid">
    <div class="d-flex">
      <i class="fas fa-compact-disc checkout-icon-adjust"></i>
      <div class="d-flex flex-column justify-content-center">
        <div style="font-weight: 500; font-size: 1.2rem">Collection of <%= collection.tracks.count %> tracks for <%= humanized_money(collection.price, symbol: session[:currency]) %>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center">
      <button id="list-tracks-modal-button" style="margin: 0"
              data-collection-checkout-modal-target="button"
              data-action="click->collection-checkout-modal#modalDisplay">
        List of tracks
      </button>
    </div>
    <div class="d-flex flex-column justify-content-center">
      <div class="d-flex justify-content-end">
        <% if SolidQueue::Job.where(class_name: "ZipCollectionJob").any? { |job| job.arguments["arguments"][0]["collection"].present? && job.arguments["arguments"][0]["order"].to_i == order.id } && (!collection.download_links.present? || collection.download_links.last.expired?) %>
          <div class="loader"></div>
        <% elsif collection.download_links.present? && !collection.download_links.last.expired? %>
          <a href="<%= collection.download_links.last.url %>"
             id="btn-download-collection"
             data-controller="delete-job"
             data-action="click->delete-job#delete"
             data-delete-job-job-id-value="<%= collection.download_links.last.job_id %>">
            Click to download
          </a>
        <% else %>
          <%= link_to "Get Download Link", create_zip_collection_path(collection: collection, order: order), id: "btn-download-get-link", data: { action: "click->collection-checkout-modal#download"} %>
        <% end %>
      </div>
    </div>
  </div>


  <!-- Collection List Modal -->
  <div id="collectionModal" class="track-list-modal" data-collection-checkout-modal-target="collectionModal">
    <!-- Modal content -->
    <div class="collection-modal-content">
      <div class="d-flex justify-content-between">
        <h3>List of tracks in your Collection</h3>
        <span class="close"
              data-collection-checkout-modal-target="close"
              data-action="click->collection-checkout-modal#modalClose">&times;
        </span>
      </div>
      <hr>

        <% collection.tracks.each do |track| %>
          <% displayed_track = SingleTrack.find(track) %>
          <div class="grid-display-list">
            <div><%= sanitize SingleTrack.categories[displayed_track.category.to_sym].to_s %></div>
            <div><%= displayed_track.title %></div>
            <div><%= link_to "Download", download_single_path(url: SingleTrack.find(track).link, title: SingleTrack.find(track).title) %></div>
          </div>
        <% end %>

    </div>
  </div>

  <!-- Download will start modal -->
  <div class="download-modal" data-collection-checkout-modal-target="downloadModal">
    <div class="download-modal-content">
      <div class="d-flex justify-content-between" id="zipping-modal-text">
        <p data-collection-checkout-modal-target="modalText">
          Zipping File: Your download link will be ready shortly
        </p>
        <span class="close"
          data-collection-checkout-modal-target="close"
          data-action="click->collection-checkout-modal#downloadModalClose">&times;
        </span>
      </div>
      <div class="d-flex justify-content-center">
        <div data-collection-checkout-modal-target="loading" class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_dashboard_collection_tracks_mobile.html.erb
<div data-controller="collection-checkout-modal">
  <div class="">
    <div class="d-flex">
      <i class="fas fa-compact-disc checkout-icon-adjust"></i>
      <div class="d-flex flex-column justify-content-center">
        <div style="font-weight: 500; font-size: 1.2rem">
          <h4 id="title-collection">Collection of <%= collection.tracks.count %> tracks</h4>
          <h5 id="price-pack">Price: <%= humanized_money(collection.price, symbol: session[:currency]) %></h5>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-center list-tracks-modal-button-wrapper">
      <button id="list-tracks-modal-button" style="margin: 0"
              data-collection-checkout-modal-target="button"
              data-action="click->collection-checkout-modal#modalDisplay">
        List of tracks
      </button>
    </div>
    <div class="d-flex flex-column justify-content-center">
      <div class="d-flex justify-content-center">
        <% if SolidQueue::Job.where(class_name: "ZipCollectionJob").any? { |job| job.arguments["arguments"][0]["collection"].present? && job.arguments["arguments"][0]["order"].to_i == order.id } && (!collection.download_links.present? || collection.download_links.last.expired?) %>
          <div class="loader"></div>
        <% elsif collection.download_links.present? && !collection.download_links.last.expired? %>
          <a href="<%= collection.download_links.last.url %>"
             id="btn-download-collection"
             data-controller="delete-job"
             data-action="click->delete-job#delete"
             data-delete-job-job-id-value="<%= collection.download_links.last.job_id %>">
            Click to download
          </a>
        <% else %>
          <%= link_to "Get Download Link", create_zip_collection_path(collection: collection, order: order), id: "btn-download-get-link", data: { action: "click->collection-checkout-modal#download"} %>
        <% end %>
      </div>
    </div>
  </div>


  <!-- Collection List Modal -->
  <div id="collectionModal" class="track-list-modal" data-collection-checkout-modal-target="collectionModal">
    <!-- Modal content -->
    <div class="collection-modal-content">
      <div class="d-flex justify-content-between">
        <h3>List of tracks in your Collection</h3>
        <span class="close"
              data-collection-checkout-modal-target="close"
              data-action="click->collection-checkout-modal#modalClose">&times;
        </span>
      </div>
      <hr>

        <% collection.tracks.each do |track| %>
          <% displayed_track = SingleTrack.find(track) %>
          <div class="grid-display-list">
            <div><%= sanitize SingleTrack.categories[displayed_track.category.to_sym].to_s %></div>
            <div><%= displayed_track.title %></div>
            <div><%= link_to "Download", download_single_path(url: SingleTrack.find(track).link, title: SingleTrack.find(track).title) %></div>
          </div>
        <% end %>

    </div>
  </div>

  <!-- Download will start modal -->
  <div class="download-modal" data-collection-checkout-modal-target="downloadModal">
    <div class="download-modal-content">
      <div class="d-flex justify-content-between" id="zipping-modal-text">
        <p data-collection-checkout-modal-target="modalText">Zipping File: Your download will start shortly</p>
        <span class="close"
          data-collection-checkout-modal-target="close"
          data-action="click->collection-checkout-modal#downloadModalClose">&times;
        </span>
      </div>
      <div class="d-flex justify-content-center">
        <div data-collection-checkout-modal-target="loading" class="lds-roller"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar_admin.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-lewagon-black">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="d-flex">
      <div><%= image_tag asset_path('logo/logo_BAM_5.png') %></div>
      <div id="text-logo">Sound Effects</div>
      <div id="text-logo-small">SFX</div>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Admin", admin_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "Eula", eula_path, class: "nav-link text-white" %>
      </li>
      <% if current_user %>
        <li class="nav-item dropdown">
          <%= image_tag asset_path("logo/avatar.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <div class="d-flex">
              <div>
                <%= link_to "Your Cart", cart_path, class: "dropdown-item"%>
              </div>
              <div>
                <% if current_user.cart && current_user.cart.items.count %>
                  <%= link_to "(#{current_user.cart.items.count})", cart_path, class: "dropdown-item", id:"cart-count"%>
                <% end %>
              </div>
            </div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_eula.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-lewagon-black">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="d-flex">
      <div><%= image_tag asset_path('logo/logo_BAM_5.png') %></div>
      <div id="text-logo">Sound Effects</div>
      <div id="text-logo-small">SFX</div>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="new-single-tracks">
    <%= link_to "Collections", list_path, class: "single-track-link" %>
    <%= image_tag asset_path('New_pale_green_transp.png'), class: "new_sticker" %>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "Track-List", list_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Eula", eula_path, class: "nav-link text-white" %>
      </li>
      <% if current_user %>
        <li class="nav-item dropdown">
          <%= image_tag asset_path("logo/avatar.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <div class="d-flex">
              <div>
                <%= link_to "Your Cart", cart_path, class: "dropdown-item"%>
              </div>
              <div>
                <% if current_user.cart && current_user.cart.items.count %>
                  <%= link_to "(#{current_user.cart.items.count + current_user.cart.sinlge_tracks.count + current_user.cart.collections.count})", cart_path, class: "dropdown-item", id:"cart-count"%>
                <% end %>
              </div>
            </div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_general.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-lewagon-black">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="d-flex">
      <div><%= image_tag asset_path('logo/logo_BAM_5.png') %></div>
      <div id="text-logo">Sound Effects</div>
      <div id="text-logo-small">SFX</div>
    </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="new-single-tracks">
    <%= link_to "Collections", list_path, class: "single-track-link" %>
    <%= image_tag asset_path('New_pale_green_transp.png'), class: "new_sticker" %>
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "Track-List", list_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link text-white" %>
      </li>

      <% if current_user %>
        <li class="nav-item dropdown">
          <%= image_tag asset_path("logo/avatar.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <div class="d-flex">
              <div>
                <%= link_to "Your Cart", cart_path, class: "dropdown-item"%>
              </div>
              <div>
                <% if current_user.cart && current_user.cart.items.count %>
                  <%= link_to "(#{current_user.cart.items.count + current_user.cart.sinlge_tracks.count + current_user.cart.collections.count})", cart_path, class: "dropdown-item", id:"cart-count"%>
                <% end %>
              </div>
            </div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_single_tracks.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="navbar-left">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class="d-flex">
        <div><%= image_tag asset_path('logo/logo_BAM_5.png') %></div>
        <br>
        <div id="text-logo">Sound Effects</div>
        <div id="text-logo-small">SFX</div>
      </div>
    <% end %>
  </div>

  <div class="navbar-center">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>

  <div class="navbar-right collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user && current_user.email == "olivier@bamsfx.com" %>
        <li class="nav-item">
          <%= link_to "Admin", admin_path, class: "nav-link text-white" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Track-List", list_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link text-white" %>
      </li>
      <% if current_user %>
        <li class="nav-item dropdown">
          <%= image_tag asset_path("logo/avatar.png"), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <div class="d-flex">
              <div>
                <%= link_to "Your Cart", cart_path, class: "dropdown-item"%>
              </div>
              <div>
                <% if current_user.cart && current_user.cart.items.count %>
                  <%= link_to "(#{current_user.cart.items.count + current_user.cart.sinlge_tracks.count + current_user.cart.collections.count})", cart_path, class: "dropdown-item", id:"cart-count"%>
                <% end %>
              </div>
            </div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_order_card_collection_desktop.html.erb
<%= link_to "List of tracks", "#" %>
<%= link_to "download all", create_zip_collection_path(collection: @collection) %>

app/views/shared/_order_card_single_tracks_desktop.html.erb
<ul>
  <% @tracks.each do |track_id| %>
    <li>
      <% if SingleTrack.exists?(id: track_id) %>
        <% track = SingleTrack.find(track_id) %>
        <%= track.title %>
        <%= link_to "download", download_single_path(url: track.link, title: track.title) %>
      <% else %>
        <p>This track no longer exists</p>
      <% end %>
    </li>
  <% end %>
</ul>
<%= link_to "download all", create_zip_path(tracks: @tracks) %>

app/views/shared/_tablet_pack_show.html.erb
<div class="mb-5 pack-box">
  <div class="d-flex justify-content-between tablet-pack-title">
    <h1 class="pack-title"><%= @pack.title %></h1>
    <div>
      <% if @discount %>
        <div>
          <div>
            <h1 id="price-sale"><%= humanized_money(@pack.price * ((100 - @discount) / 100.to_f), symbol: session[:currency]) %></h1>
          </div>
          <div>
            <h4 id="price-barred-show" > <strike><%= humanized_money(@pack.price, symbol: session[:currency]) %></strike> </h4>
          </div>
        </div>
      <% else %>
        <h1 id="price"><%= humanized_money(@pack.price, symbol: session[:currency]) %></h1>
      <% end %>
    </div>
  </div>
  <p id="sound-designer">Sound Designer: <%= link_to @designer_name, about_path %> </p>
  <div class="d-flex">
    <div class="pic-price">
      <% @pack.photos.each do |photo| %>
        <%= image_tag photo %>
      <% end %>

      <% if @discount %>
        <div><%= image_tag asset_path('Promo_orange.png'), id: "sale-show" %>
          <p id="sale-percentage-show"><%= @discount %>%<br>OFF</p>
        </div>
      <% end %>

    </div>
    <div class="description-box">
      <ul>
        <li>
          <% if @pack.size_mb >= 1000  %>
            <%= @pack.size_mb / 1000.to_f %> GB
          <% else %>
            <%= @pack.size_mb %> MB
          <% end %>
        </li>
        <li><%= @pack.duration %> minutes</li>
        <li><%= number_with_delimiter @pack.number_of_tracks %> tracks</li>
        <li id="desktop-file-caracteristics">48 kHz / 24bit / Stereo WAV files</li>
        <li><div id="tablet-file-caracteristics">48 kHz / 24bit / WAV</div></li>
        <li><%= link_to "List of Sounds", @pack.sound_list.url, target: :_blank %></li>
        <li>Version: <%= @pack.version %></li>
        <li id='pack-description'>Description: <%= @pack.description %></li>
      </ul>
    </div>
  </div>
  <% if @pack.sku.include?("FS") %>
    <div class="d-flex align-items-center">
      <%= button_to "Download", @pack.product_link, method: :get, id: 'btn-download', class: 'ml-4' %>
    </div>
  <% else %>
    <div class="d-flex justify-content-between">
      <div>
      <%= form_tag orders_path do %>
        <%= hidden_field_tag 'pack_id', @pack.id %>
        <%= submit_tag 'Buy now', id: 'purchase-btn' %>
      <% end %>
      </div>
      <div>
        <%= form_tag cart_order_path do %>
          <%= hidden_field_tag 'pack_id', @pack.id %>
          <%= submit_tag 'Add to Cart', id: 'btn-cart-show' %>
        <%  end %>
      </div>
    </div>
  <% end %>
</div>