config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails-admin', as: 'rails_admin'

  authenticate :user, ->(u) { u.admin? } do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end

  get 'collections/create'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "dashboard", to: "dashboards#dashboard"
  get "unsubscribe", to: "dashboards#unsubscribe"
  get "subscribe", to: "dashboards#subscribe"
  post "cart_order", to: "carts#cart_order"
  post "single_tracks_cart", to: "carts#single_tracks"
  get "cart", to: "carts#cart"
  post "remove_item", to: "carts#delete_item"
  get "remove_track", to: "carts#delete_track"
  post "single_tracks_cart_remove", to: "carts#single_tracks_cart_remove"
  post "checkout", to: "orders#checkout"
  get "destroy_order", to: "orders#destroy"
  get "update_order_status", to: "orders#update_order_status"
  get "destroy_order_dashboard", to: "orders#destroy_from_dashboard"
  get "destroy_cart", to: "carts#destroy_cart"
  get "about", to: "pages#about"
  get "eula", to: "pages#eula"
  get "blog", to: "pages#blog"
  get "the_quest", to: "pages#the_quest"
  post "subscribe_no_user", to: "pages#subscribe"
  resources :sfx_packs, only: [:show, :index]

  resources :sound_designers, only: [:new, :create, :show] do
    resources :sfx_packs, only: [:create, :update]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  resources :sales, only: [:new, :create, :destroy]

  get 'list', to: 'single_tracks#index'
  get 'download_single', to: 'single_tracks#download_single'
  get 'create_zip', to: 'single_tracks#create_zip'
  get 'create_zip_collection', to: 'collections#create_zip_collection'

  resources :collections, only: [:create, :update, :show]
  post "name_update", to: "collections#name_update"
  post "convert", to: "collections#convert"
  post "remove_collection_from_cart", to: "collections#remove_collection_from_cart"
  delete "destroy_collection", to: "collections#destroy_collection"

  # create collection template --> admin
  post "create_collection_template", to: "collections#create_template"
  get "collection_templates", to: "collections#templates_index"
  get "collection_templates/:id", to: "collections#templates_show", as: :collection_template

  # user add template to cart and convert into collection
  get "add_template_to_cart", to: "collections#add_template_to_cart"

  # Sound Designer Submission
  resources :designer_submissions, param: :access_token, only: %i(new create show update) do
    resources :submission_links, only: :create
  end

  resources :designer_submissions, only: :destroy
  resources :submission_links, only: :destroy

  # thank you for your submission
  get "thank_you", to: "designer_submissions#thank_you", as: :thank_you

  # admin routes
  get "admin", to: "administrator#admin"
  get "admin/designer_submissions", to: "administrator#designer_submissions", as: :submissions
  get "admin/designer_legal_entities", to: "administrator#designer_legal_entities", as: :legal_entities_submissions
  get "admin/pack_submissions", to: "administrator#pack_submissions", as: :pack_submissions
  get "admin/designers_list", to: "administrator#designers_list", as: :designers_list
  get "admin/designers_offline", to: "administrator#designers_offline_list", as: :designers_offline_list
  get "admin/designers_rejected", to: "administrator#designers_rejected_list", as: :designers_rejected_list
  get "admin/designers/:id/packs", to: "administrator#designer_packs", as: :designer_packs
  patch "submission_accepted/:id", to: "administrator#submission_accepted", as: :submission_accepted
  patch "submission_rejected/:id", to: "administrator#submission_rejected", as: :submission_rejected
  post "admin/resend_confirmation/:user_id", to: "administrator#resend_confirmation", as: :resend_confirmation
  patch "pack_accepted/:id", to: "administrator#pack_accepted", as: :sfx_pack_accepted
  patch "pack_rejected/:id", to: "administrator#pack_rejected", as: :sfx_pack_rejected
  get "admin/stats", to: "administrator#stats", as: :stats
  get "admin/sales", to: "administrator#sales", as: :list_sales
  get "admin/payouts", to: "administrator#payouts", as: :admin_payouts
  get "admin/agreements", to: "administrator#agreements", as: :admin_agreements
  get "calculate_exchange_rate", to: "administrator#calculate_exchange_rate", as: :calculate_exchange_rate
  get "admin/legal_entity/:id", to: "administrator#legal_entity", as: :legal_entity
  patch "admin/legal_entity_accept/:id", to: "administrator#legal_entity_accept", as: :legal_entity_accept
  patch "admin/legal_entity_reject/:id", to: "administrator#legal_entity_reject", as: :legal_entity_reject
  post "admin/reject_designer/:designer_id", to: "administrator#reject_designer", as: :reject_designer
  patch "admin/paypal_accept/:id", to: "administrator#paypal_accept", as: :paypal_accept
  patch "admin/paypal_reject/:id", to: "administrator#paypal_reject", as: :paypal_reject
  resources :payouts, only: [:new, :create]

  # sound designer dashboard routes
  get "designer_dashboard", to: "designer_dashboards#main", as: :designer_main_dashboard
  get "your_listings", to: "designer_dashboards#listings", as: :designer_listings
  get "sales", to: "designer_dashboards#sales", as: :designer_sales
  get "payouts", to: "designer_dashboards#payouts", as: :designer_payouts
  get "settings", to: "designer_dashboards#settings", as: :settings
  get "add_new_pack", to: "designer_dashboards#pack_form", as: :add_new_pack
  get "update_pack/:id", to: "designer_dashboards#update_pack_form", as: :update_pack
  delete "remove_pack/:id", to: "designer_dashboards#remove_pack", as: :remove_pack
  post "sound_designers/:id/paypal_account", to: "designer_dashboards#paypal_account", as: :paypal_account
  post "sound_designers/:id/update_info", to: "designer_dashboards#update_designer_info", as: :update_designer_info
  post "sound_designers/:id/update_bio", to: "designer_dashboards#update_designer_bio", as: :update_designer_bio
  post "sound_designers/:id/update_photo", to: "designer_dashboards#update_designer_photo", as: :update_designer_photo
  post "sound_designers/:id/banner", to: "designer_dashboards#banner", as: :designer_banner

  # legal entities
  resources :legal_entities, only: [:new, :create, :edit, :update]

  # agreements
  get "agreements/:key/:version", to: "agreements#show", as: :agreement
  delete "agreements/:key/:version", to: "agreements#destroy", as: :delete_agreement
  get "agreements/:key/:version/deactivate", to: "agreements#deactivate", as: :deactivate_agreement
  get "agreements/:key/:version/activate", to: "agreements#activate", as: :activate_agreement
  get "agreements/:key/:version/pdf", to: "agreements#pdf", as: :pdf_agreement
  get "sound_designers/:id/seller_agreement", to: "agreements#seller_agreement", as: :seller_agreement

  # agreement acceptances
  resources :sound_designers, only: [] do
    resources :agreement_acceptances, only: :create
  end

  # data protection path
  get "data_protection", to: "pages#data_protection"

  # modal close path
  get "modal_closed", to: "pages#modal_closed"

  # jobs routes
  delete "jobs/:job_id", to: "jobs#destroy", as: :job

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # post "/webhooks/stripe", to: "stripe_webhook#receive"
end

app/controllers/designer_dashboards_controller.rb
class DesignerDashboardsController < ApplicationController
  before_action :unauthenticated_redirect, :new_designer, :check_legal_entity, :load_designer, :agreement_signed
  before_action :load_pack, only: [:update_pack_form, :remove_pack]

  def main
  end

  def listings
    # @live_packs = @designer.sfx_packs.live.order(updated_at: :desc)
    # @pending_packs = @designer.sfx_packs.pending.order(updated_at: :desc)
    # @under_review_packs = @designer.sfx_packs.under_review.order(updated_at: :desc)
    # @declined_packs = @designer.sfx_packs.declined.order(updated_at: :desc)

    @packs = @designer.sfx_packs.where.not(id: 100).order(:status)
    @pack_count = {
      all: @packs.count,
      live: @packs.live.count,
      submitted: @packs.submitted.count,
      declined: @packs.declined.count,
      drafts: @packs.draft.count,
      removed: @packs.removed.count
    }
  end

  def sales
    @sold_items = @designer.sold_items.where(status: 'pending').includes(:sfx_pack).joins(:order).where(order: {status: "paid"}).order(created_at: :desc)
    @past_sold_items = @designer.sold_items.where(status: 'paid').includes(:sfx_pack).joins(:order).where(order: {status: "paid"}).order(created_at: :desc)
    @payout_amount = @sold_items.sum { |payout| payout.payout_amount_cents if payout.status != "paid"} / 100.0
    @currency_symbol = CurrencySymbolService.lookup(@designer.user.legal_entity.payment_infos.last.preferred_currency)
    @start_date = @sold_items.first.order.created_at.to_date.beginning_of_month.to_s if @sold_items.present?
    @end_date = Date.today.to_s
    if params[:filters].present? && params[:filters][:range_date].present?
      @start_date = params[:filters][:range_date].split("to").first.strip
      @end_date = params[:filters][:range_date].split("to").last.strip
      @sold_items = @sold_items.select do |item|
        item.order.created_at.to_date >= @start_date.to_date && item.order.created_at.to_date <= @end_date.to_date
      end
      @past_sold_items = @past_sold_items.select do |item|
        item.order.created_at.to_date >= @start_date.to_date && item.order.created_at.to_date <= @end_date.to_date
      end
    end
  end

  def payouts
    @sold_items = @designer.sold_items.where(status: 'pending').includes(:sfx_pack).joins(:order).where(order: {status: "paid"}).order(created_at: :desc)
    @payout_amount = @sold_items.sum { |payout| payout.payout_amount_cents if payout.status != "paid"} / 100.0
    @payouts = Payout.where(legal_entity: @designer.legal_entity, status: "paid").order(payout_date: :desc)
    @year = Date.today.year
    @currency_symbol = CurrencySymbolService.lookup(@designer.user.legal_entity.payment_infos.last.preferred_currency)
    if @payouts.present?
      @prior_year_payments = @payouts.first.payout_date.year != @payouts.last.payout_date.year
      @first_payout_year = @payouts.last.payout_date.year
      if params[:filters].present? && params[:filters][:year].present?
        @payouts = @payouts.select { |payout| payout.payout_date.year == params[:filters][:year].to_i }
        @year = params[:filters][:year].to_i
      else
        @payouts = @payouts.select { |payout| payout.payout_date.year == Date.today.year }
      end
    end
  end

  def settings
    @legal_entity = current_user.legal_entity
  end

  def pack_form
    @designer = current_user.sound_designer
    @sfx_pack = SfxPack.new
  end

  def update_pack_form
    @designer = @sfx_pack.sound_designer
    redirect_to designer_listings_path, notice: "You do not have authorisation to access this page" if current_user != @designer.user && !current_user.admin?
  end

  def remove_pack
    @sfx_pack.removed!
    redirect_to designer_listings_path
  end

  def paypal_account
    @paypal.update(payment_params)
    raise
    # ! this is where we need to re-organise everything
    @paypal.user = @designer.user
    @paypal.preferred_currency = params[:payment_info][:preferred_currency].downcase
    @paypal.save
    redirect_to designer_main_dashboard_path, notice: "Paypal account updated"
  end

  def update_designer_info
    @designer.update(designer_params)
    @designer.user.save if @designer.user.changed?
    if @designer.save
      redirect_to designer_main_dashboard_path, notice: "Information updated"
    else
      render :main, status: :unprocessable_entity
    end
  end

  def update_designer_bio
    @designer.update(bio_params)
    if @designer.save
      redirect_to designer_main_dashboard_path, notice: "Bio updated"
    else
      render :main, status: :unprocessable_entity
    end
  end

  def update_designer_photo
    @designer.photo.attach(photo_params[:photo])
    if @designer.save(validate: false)
      redirect_to designer_main_dashboard_path, notice: "Photo updated"
    else
      render :main, status: :unprocessable_entity
    end
  end

  def banner
    @designer.banner.attach(params[:sound_designer][:banner])
    if @designer.save(validate: false)
      redirect_to designer_main_dashboard_path, notice: "Banner updated"
    else
      render :main, status: :unprocessable_entity
    end
  end

  private

  def check_legal_entity
    unless current_user.admin?
      if !current_user.legal_entity.present?
        redirect_to new_legal_entity_path
      elsif current_user.legal_entity.incomplete?
        redirect_to edit_legal_entity_path
      elsif !current_user.designer && !current_user.sound_designer.present?
        redirect_to root_path, notice: "You need a seller account to access this page!"
      end
    end
  end

  def load_designer
    if current_user.admin && params[:designer_id].present?
      @designer = SoundDesigner.find(params[:designer_id])
    else
      @designer = current_user.sound_designer
      if @designer.user.legal_entity.nil?
        redirect_to new_legal_entity_path
      else
        @paypal = @designer.user.legal_entity.payment_infos.last || @designer.user.legal_entity.payment_infos.new
      end
    end
  end

  def unauthenticated_redirect
    redirect_to root_path, notice: "You need to sign in to access this page" if !user_signed_in?
  end

  def new_designer
    redirect_to new_sound_designer_path if user_signed_in? && current_user.designer && current_user.sound_designer.nil?
  end

  def load_pack
    @sfx_pack = SfxPack.find(params[:id])
  end

  def payment_params
    params.require(:payment_info).permit(:paypal_account)
  end

  def designer_params
    params.require(:sound_designer).permit(:artist_name, :location)
  end

  def bio_params
    params.require(:sound_designer).permit(:bio)
  end

  def photo_params
    params.require(:sound_designer).permit(:photo)
  end

  def agreement_signed
    @agreement_signed = @designer.user.legal_entity.agreement_acceptances.where(agreement: Agreement.where(active: true)).exists?

    # this shows the agreement template. we nee to generate the custom agreement for the designer
    @agreement_acceptance = @designer.user.legal_entity.agreement_acceptances.where(agreement: Agreement.where(active: true)).last if @agreement_signed
    @agreement = Agreement.find(@agreement_acceptance.agreement_id) if @agreement_acceptance
  end
end

app/helpers/designer_dashboards_helper.rb
module DesignerDashboardsHelper
end

app/views/designer_dashboards/_designer_menu_mobile.html.erb
<div class="d-flex mt-4 mb-2 designer-menu__xs-display">
  <%= link_to "Listings", designer_listings_path, class: "btn btn-secondary me-2 btn-admin  #{'btn-admin-active' if controller_name == "designer_dashboards" && action_name == "listings"}" %>
  <%= link_to "Sales", designer_sales_path, class: "btn btn-secondary me-2 btn-admin  #{'btn-admin-active' if controller_name == "designer_dashboards" && action_name == "sales"}" %>
  <%= link_to "Payouts", designer_payouts_path, class: "btn btn-secondary me-2 btn-admin #{'btn-admin-active' if controller_name == "designer_dashboards" && action_name == "payouts"}" %>
  <%= link_to "Profile", designer_main_dashboard_path, class: "btn btn-secondary me-2 btn-admin #{'btn-admin-active' if controller_name == "designer_dashboards" && action_name == "main"}" %>
  <%= link_to "Settings", settings_path, class: "btn btn-secondary me-2 btn-admin #{'btn-admin-active' if controller_name == "designer_dashboards" && action_name == "settings"} designer-menu__mobile-settings-tab" %>
  <div class="designer-menu__xs-support-tab">
    <a href="mailto: support@bamsfx.com" target="blank" class="btn btn-secondary btn-admin">Support</a>
  </div>
</div>
<%= link_to "Settings", settings_path, class: "btn btn-secondary btn-admin #{'btn-admin-active' if controller_name == "designer_dashboards" && action_name == "settings"} designer-menu__xs-settings-tab" %>
<hr style="border-color: white">

app/views/designer_dashboards/_filter_pills_mobile.html.erb
<div class="d-flex mb-3 designer-menu__mobile-filter-pills__font-size" style="overflow-x: scroll">
  <span class="text-white me-2 px-3 py-2 badge rounded-pill designer-dashboard__packs-filter-pills active" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">all</span>
  <span class="text-white me-2 px-3 py-2 badge rounded-pill designer-dashboard__packs-filter-pills" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">live</span>
  <span class="text-white me-2 px-3 py-2 badge rounded-pill designer-dashboard__packs-filter-pills" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">submitted</span>
  <span class="text-white me-2 px-3 py-2 badge rounded-pill designer-dashboard__packs-filter-pills" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">declined</span>
  <span class="text-white me-2 px-3 py-2 badge rounded-pill designer-dashboard__packs-filter-pills" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">drafts</span>
  <span class="text-white me-2 px-3 py-2 badge rounded-pill designer-dashboard__packs-filter-pills" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">removed</span>
  <%= link_to add_new_pack_path do %>
    <span class="text-white px-3 py-2 badge rounded-pill designer-dashboard__packs-filter-pills" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter"><i class="fas fa-plus"></i></span>
  <% end %>
</div>

app/views/designer_dashboards/_welcome_banner.html.erb
<div class="designer-dashboard__welcome">
  <div class="container">
    <div class="designer-dashboard__banner" style="background-image: url('<%= url_for(@designer.banner) if @designer.banner.attached? %>')">
      <div class="designer-dashboard__banner-designer-photo"
           data-controller="photo-upload submission-image-preview"
           data-action="click->photo-upload#trigger">
        <div class="designer-dashboard__banner-photo-display">
          <% if @designer.photo.attached? %>
            <%= image_tag @designer.photo, class: "pack-submission-form__image-placeholder", data: {submission_image_preview_target: "preview"} %>
          <% else %>
            <img src="https://res.cloudinary.com/dk9a86uhu/image/upload/v1753797330/sfx_shop/placeholder_dbrvpk.png" alt="image placeholder" class="pack-submission-form__image-placeholder" data-submission-image-preview-target="preview">
          <% end %>
          <i class="fas fa-camera" data-photo-upload-target="icon"></i>
        </div>
        <div data-photo-upload-target="form" class="d-none designer-dashboard__banner-photo-form">
          <%= simple_form_for @designer, url: update_designer_photo_path(@designer), method: :post do |f| %>
            <div class="designer-dashboard__banner-photo-form-inputs">
              <%= f.input :photo, as: :file, label: false, input_html: {data: { submission_image_preview_target: "input", action: "change->submission-image-preview#preview" }} %>
              <div class="d-flex designer-dashboard__banner-image-form-buttons">
                <%= f.submit "Upload", class: "btn btn-light", id: "submit", style: "color: black" %>
                <div class="btn btn-light ms-2 designer-dashboard__banner-image-form-icon" style="color: black" data-action="click->photo-upload#hide">
                  <strong>X</strong>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div data-controller="banner-form">
        <div class="d-flex justify-content-end designer-dashboard__banner-icon"
             data-action="click->banner-form#displayForm"
             data-banner-form-target="icon">
          <i class="fas fa-pen"></i>
        </div>
        <% unless @designer.banner.attached? %>
          <h5>Add A Banner to your profile</h5>
        <% end %>
        <div class="d-none designer-dashboard__banner-image-form" data-banner-form-target="form">
          <%= simple_form_for @designer, url: designer_banner_path(@designer), method: :post do |f| %>
            <div class="designer-dashboard__banner-photo-form-inputs">
              <%= f.input :banner, as: :file, label: false %>
              <div class="designer-dashboard__banner-image-form-buttons">
                <%= f.submit "Upload", class: "btn btn-light", id: "submit", style: "color: black" %>
                <div class="btn btn-light ms-2 designer-dashboard__banner-image-form-icon" style="color: black" data-action="click->banner-form#hideForm">
                  <i class="fas fa-times"></i>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="designer-dashboard__banner-artist-name">
        <span><%= @designer.artist_name %></span>
      </div>
    </div>
  </div>
</div>

app/views/designer_dashboards/pack_form.html.erb
<div class="dark-background">
  <div class="submission-form__container">
    <div class="submission-form__back-button-position">
      <%= link_to designer_listings_path, class: "submission-form__back-button" do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
    </div>
    <div class="submission-form__conditions-banner">
      Reminder: By submitting your sound effects, you guarantee that the sound effects submitted comply to the <strong>Content Submission Rules</strong> stated in the <strong><%= link_to "signed agreement", seller_agreement_path(@designer), target: "_blank" %></strong>.
    </div>
    <div class="pack-submission-form__box">
      <div class="text-center">
        <h4>Pack Submission Form</h4>
      </div>
      <hr>
      <%= render "designer_dashboards/pack_submission_form" %>
    </div>
    <div style="height: 40px"></div>
  </div>
</div>

app/views/designer_dashboards/payouts.html.erb
<div class="padding-navbar content admin-min-height bg-dark pb-4">
  <%= render "welcome_banner" %>
  <div class="container">
    <div class="designer-menu__desktop">
      <%= render "designer_menu" %>
    </div>
    <div class="designer-menu__mobile">
      <%= render "designer_menu_mobile" %>
    </div>
    <% if @designer.invalid?%>
      <div class="designer-dashboard__no-payout">
        <h4 class="designer-dashboard__info-banner"> Please complete your profile to continue <%= link_to "Click here", designer_main_dashboard_path(@designer), class: "btn btn-reject" %></h4>
      </div>
    <% elsif !@agreement_signed && @designer.valid? %>
      <div class="designer-dashboard__no-payout">
        <h4 class="designer-dashboard__info-banner"> Please review the Seller Agreement to proceed <%= link_to "Click here", seller_agreement_path(@designer), class: "btn btn-orange ms-4"%></h4>
      </div>
    <% elsif !current_user.legal_entity.accepted? && !current_user.admin?%>
      <div class="d-flex justify-content-center btn btn-orange btn-hover-dismiss">Your submission is pending approval</div>
    <% else %>
    <div class="d-flex justify-content-between">
      <div style="color: white; opacity: 0.7">Next payout: <%= humanized_money(@payout_amount, symbol: "#{@currency_symbol} ") %></div>
      <% if @prior_year_payments %>
        <%= simple_form_for :filters, url: payouts_path, method: :get, html: {class: "designer-dashboard__payout-form"} do |f| %>
          <div class="d-flex">
            <%= f.input :year,
                        collection: (@first_payout_year..Date.today.year).to_a.reverse,
                        selected: params[:filters].present? && params[:filters][:year].present? ? params[:filters][:year] : Date.today.year,
                        include_blank: false,
                        label: false,
                        required: false,
                        wrapper_input_html: { class: "designer-dashboard__payout-year-select" } %>
            <%= button_tag type: :submit, class: "btn" do %>
               <i class="fas fa-check"></i>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <div class="btn btn-secondary"><%= @year %></div>
      <% end %>
    </div>
    <div class="designer-dashboard__payouts-desktop">
      <%= render "payouts_list_desktop" %>
    </div>
    <div class="designer-dashboard__payouts-mobile">
      <%= render "payouts_list_mobile" %>
    </div>
    <% end %>
  </div>
</div>

app/views/designer_dashboards/submissions.html.erb
<%= render "shared/left_pannel_mobile"%>
<div class="padding-navbar content admin-min-height bg-dark">
  <div class="designer-dashboard__welcome">
    <h3>Welcome to your designer dashboard!</h3>
  </div>
  <div class="container" data-controller="designer-pack-filter">
    <%= render "designer_menu" %>
    <div class="d-flex justify-content-between">
      <div class="mb-3">
        <span style="color: whitesmoke !important; margin-right: 8px; font-size: 0.8rem !important">Filter:</span>
        <span class="text-white px-3 py-1 badge rounded-pill designer-dashboard__packs-filter-pills active" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">all</span>
        <span class="text-white px-3 py-1 badge rounded-pill designer-dashboard__packs-filter-pills" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">live</span>
        <span class="text-white px-3 py-1 badge rounded-pill designer-dashboard__packs-filter-pills" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">submitted</span>
        <span class="text-white px-3 py-1 badge rounded-pill designer-dashboard__packs-filter-pills" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">declined</span>
        <span class="text-white px-3 py-1 badge rounded-pill designer-dashboard__packs-filter-pills" data-designer-pack-filter-target="pill" data-action="click->designer-pack-filter#filter">drafts</span>
      </div>
      <div>
        <%= link_to add_new_pack_path do %>
          <span class="px-3 py-1 rounded-pill designer-dashboard__add-pack-pill"><i class="fas fa-plus"></i> Add a Pack</span>
        <% end %>
      </div>
    </div>
    <div class="submissions-live__grid">
      <% @packs.each do |pack| %>
        <% case pack.status %>
        <% when "live" then pill_color_class = "live" %>
        <% when "declined" then pill_color_class = "declined" %>
        <% else pill_color_class = "else" %>
        <% end %>
        <div class="designer-dashboard__container mb-3"
             data-designer-pack-filter-target="status"
             data-status="<%= pack.status %>">
          <div class="designer-dashboard__user-profile">
            <div class="d-flex justify-content-between">
              <div>
                <%= pack.title %><span class="badge rounded-pill text-bg-light ms-3 <%= pill_color_class %>"><%= pack.status %></span>
              </div>
              <div>
                <%= link_to sfx_pack_path(pack), target: "_blank" do %>
                  <i class="fas fa-eye me-2"></i>
                <% end %>
                <%= link_to update_pack_path(pack), class: "designer-dashboard__icon-white" do %>
                  <i class="fas fa-pen"></i>
                <% end %>
              </div>
            </div>
            <hr>
            <div class="d-flex submissions__pack-description">
              <div class="me-4">
                <% if pack.photos.present? %>
                  <%= cl_image_tag pack.photos.first.key, height: 180, width: 180, style: "border-radius: 8px" %>
                <% end %>
              </div>
              <div class="text-muted small d-flex flex-column justify-content-between">
                <div>
                  <p class="mb-1">• 48kHz / 24bit High Def Audio</p>
                  <% if pack.size_mb > 1000 %>
                    <p class="mb-1">• <%= (pack.size_mb / 1000.to_f).ceil(1) %> GB</p>
                  <% else %>
                    <p class="mb-1">• <%= pack.size_mb %> MB</p>
                  <% end %>
                  <p class="mb-1">• <%= pack.number_of_tracks %> Sounds</p>
                  <p class="mb-0">• Format: WAV</p>
                </div>
                <div class="designer-dashboard__pills">
                  <div class="flex flex-wrap gap-2 pb-2">
                    <% pack.category.split(", ").each do |tag| %>
                      <span class="text-white text-xs font-medium px-2 py-1 badge rounded-pill" style="background-color: #0d9488;"><%= tag %></span>
                    <% end %>
                  </div>
                  <div class="submissions__pack-price">
                    <% if pack.price_cents == 0 %>
                      <span class="text-white text-xs px-2 py-1 badge rounded-pill" style="background-color: #ff00fe;">free</span>
                    <% else %>
                      <div id="submissions__pack-price-font">
                        <%= number_to_currency(pack.price, unit: "$ ", separator: ",", precision: 2) %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>