config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails-admin', as: 'rails_admin'

  authenticate :user, ->(u) { u.admin? } do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end

  get 'collections/create'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "dashboard", to: "dashboards#dashboard"
  get "unsubscribe", to: "dashboards#unsubscribe"
  get "subscribe", to: "dashboards#subscribe"
  post "cart_order", to: "carts#cart_order"
  post "single_tracks_cart", to: "carts#single_tracks"
  get "cart", to: "carts#cart"
  post "remove_item", to: "carts#delete_item"
  get "remove_track", to: "carts#delete_track"
  post "single_tracks_cart_remove", to: "carts#single_tracks_cart_remove"
  post "checkout", to: "orders#checkout"
  get "destroy_order", to: "orders#destroy"
  get "update_order_status", to: "orders#update_order_status"
  get "destroy_order_dashboard", to: "orders#destroy_from_dashboard"
  get "destroy_cart", to: "carts#destroy_cart"
  get "about", to: "pages#about"
  get "eula", to: "pages#eula"
  get "blog", to: "pages#blog"
  get "the_quest", to: "pages#the_quest"
  post "subscribe_no_user", to: "pages#subscribe"
  resources :sfx_packs, only: [:show, :index]

  resources :sound_designers, only: [:new, :create, :show] do
    resources :sfx_packs, only: [:create, :update]
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  resources :sales, only: [:new, :create, :destroy]

  get 'list', to: 'single_tracks#index'
  get 'download_single', to: 'single_tracks#download_single'
  get 'create_zip', to: 'single_tracks#create_zip'
  get 'create_zip_collection', to: 'collections#create_zip_collection'

  resources :collections, only: [:create, :update, :show]
  post "name_update", to: "collections#name_update"
  post "convert", to: "collections#convert"
  post "remove_collection_from_cart", to: "collections#remove_collection_from_cart"
  delete "destroy_collection", to: "collections#destroy_collection"

  # create collection template --> admin
  post "create_collection_template", to: "collections#create_template"
  get "collection_templates", to: "collections#templates_index"
  get "collection_templates/:id", to: "collections#templates_show", as: :collection_template

  # user add template to cart and convert into collection
  get "add_template_to_cart", to: "collections#add_template_to_cart"

  # Sound Designer Submission
  resources :designer_submissions, param: :access_token, only: %i(new create show update) do
    resources :submission_links, only: :create
  end

  resources :designer_submissions, only: :destroy
  resources :submission_links, only: :destroy

  # thank you for your submission
  get "thank_you", to: "designer_submissions#thank_you", as: :thank_you

  # admin routes
  get "admin", to: "administrator#admin"
  get "admin/designer_submissions", to: "administrator#designer_submissions", as: :submissions
  get "admin/designer_legal_entities", to: "administrator#designer_legal_entities", as: :legal_entities_submissions
  get "admin/pack_submissions", to: "administrator#pack_submissions", as: :pack_submissions
  get "admin/designers_list", to: "administrator#designers_list", as: :designers_list
  get "admin/designers_offline", to: "administrator#designers_offline_list", as: :designers_offline_list
  get "admin/designers_rejected", to: "administrator#designers_rejected_list", as: :designers_rejected_list
  get "admin/designers/:id/packs", to: "administrator#designer_packs", as: :designer_packs
  patch "submission_accepted/:id", to: "administrator#submission_accepted", as: :submission_accepted
  patch "submission_rejected/:id", to: "administrator#submission_rejected", as: :submission_rejected
  post "admin/resend_confirmation/:user_id", to: "administrator#resend_confirmation", as: :resend_confirmation
  patch "pack_accepted/:id", to: "administrator#pack_accepted", as: :sfx_pack_accepted
  patch "pack_rejected/:id", to: "administrator#pack_rejected", as: :sfx_pack_rejected
  get "admin/stats", to: "administrator#stats", as: :stats
  get "admin/sales", to: "administrator#sales", as: :list_sales
  get "admin/payouts", to: "administrator#payouts", as: :admin_payouts
  get "admin/agreements", to: "administrator#agreements", as: :admin_agreements
  get "calculate_exchange_rate", to: "administrator#calculate_exchange_rate", as: :calculate_exchange_rate
  get "admin/legal_entity/:id", to: "administrator#legal_entity", as: :legal_entity
  patch "admin/legal_entity_accept/:id", to: "administrator#legal_entity_accept", as: :legal_entity_accept
  patch "admin/legal_entity_reject/:id", to: "administrator#legal_entity_reject", as: :legal_entity_reject
  post "admin/reject_designer/:designer_id", to: "administrator#reject_designer", as: :reject_designer
  patch "admin/paypal_accept/:id", to: "administrator#paypal_accept", as: :paypal_accept
  patch "admin/paypal_reject/:id", to: "administrator#paypal_reject", as: :paypal_reject
  resources :payouts, only: [:new, :create]

  # sound designer dashboard routes
  get "designer_dashboard", to: "designer_dashboards#main", as: :designer_main_dashboard
  get "your_listings", to: "designer_dashboards#listings", as: :designer_listings
  get "sales", to: "designer_dashboards#sales", as: :designer_sales
  get "payouts", to: "designer_dashboards#payouts", as: :designer_payouts
  get "settings", to: "designer_dashboards#settings", as: :settings
  get "add_new_pack", to: "designer_dashboards#pack_form", as: :add_new_pack
  get "update_pack/:id", to: "designer_dashboards#update_pack_form", as: :update_pack
  delete "remove_pack/:id", to: "designer_dashboards#remove_pack", as: :remove_pack
  post "sound_designers/:id/paypal_account", to: "designer_dashboards#paypal_account", as: :paypal_account
  post "sound_designers/:id/update_info", to: "designer_dashboards#update_designer_info", as: :update_designer_info
  post "sound_designers/:id/update_bio", to: "designer_dashboards#update_designer_bio", as: :update_designer_bio
  post "sound_designers/:id/update_photo", to: "designer_dashboards#update_designer_photo", as: :update_designer_photo
  post "sound_designers/:id/banner", to: "designer_dashboards#banner", as: :designer_banner

  # legal entities
  resources :legal_entities, only: [:new, :create, :edit, :update]

  # agreements
  get "agreements/:key/:version", to: "agreements#show", as: :agreement
  delete "agreements/:key/:version", to: "agreements#destroy", as: :delete_agreement
  get "agreements/:key/:version/deactivate", to: "agreements#deactivate", as: :deactivate_agreement
  get "agreements/:key/:version/activate", to: "agreements#activate", as: :activate_agreement
  get "agreements/:key/:version/pdf", to: "agreements#pdf", as: :pdf_agreement
  get "sound_designers/:id/seller_agreement", to: "agreements#seller_agreement", as: :seller_agreement

  # agreement acceptances
  resources :sound_designers, only: [] do
    resources :agreement_acceptances, only: :create
  end

  # data protection path
  get "data_protection", to: "pages#data_protection"

  # modal close path
  get "modal_closed", to: "pages#modal_closed"

  # jobs routes
  delete "jobs/:job_id", to: "jobs#destroy", as: :job

  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # post "/webhooks/stripe", to: "stripe_webhook#receive"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  # despite the terrible naming choice, cart_order is the action for "adding SfxPacks to the cart"
  def cart_order
    if Cart.where(user_id: current_user.id).count == 1
      @items = Cart.where(user_id: current_user.id).first
      @items.items << SfxPack.find(params[:pack_id]).id.to_i
      @items.items.uniq!
    else
      # check which of the 2 lines bellow is correct
      # @items = Cart.create(user_id: current_user.id).first
      @items = Cart.create(user_id: current_user.id)
      @items.items = []
      @items.sinlge_tracks = []
      @items.items << SfxPack.find(params[:pack_id]).id.to_i
    end
    @items.save
    redirect_to root_path(anchor: "front-title")
  end

  # adding single tracks to Cart
  def single_tracks
    if Cart.where(user_id: current_user.id).count == 1 && Cart.where(user_id: current_user.id).first.sinlge_tracks != nil
      @tracks = Cart.where(user_id: current_user.id).first
      @tracks.sinlge_tracks << SingleTrack.find(params[:track_id]).id.to_i
      @tracks.sinlge_tracks.uniq!
    elsif Cart.where(user_id: current_user.id).count == 1 && Cart.where(user_id: current_user.id).first.sinlge_tracks == nil
      @tracks = Cart.where(user_id: current_user.id).first
      @tracks.sinlge_tracks = []
      @tracks.items = []
      @tracks.sinlge_tracks << SingleTrack.find(params[:track_id]).id.to_i
      @tracks.sinlge_tracks.uniq!
    else
      @tracks = Cart.create(user_id: current_user.id)
      @tracks.sinlge_tracks = []
      @tracks.items = []
      @tracks.sinlge_tracks << SingleTrack.find(params[:track_id]).id.to_i
    end
    @tracks.save
    redirect_to request.referer
  end

  def cart
    # fetching collections
    collections
    # adding collection(s) to cart
    cart = current_user.cart
    if cart && @current_collections.last
      cart.collections << @current_collections.last.id
      cart.collections.uniq!
      cart.save
    end

    # Set a few variables
    @number_of_items = @current_collections.count
    @items = Cart.where(user_id: current_user.id).first
    current_sales = Sale.where("end_date > ?", Date.current)
    @current_sales_list = {}

    # listing all packs to sort them by price to display them and apply discount to 2nd and other packs
    if @items
      @pack_list = []
      @items.items.each do |item|
        @pack_list << SfxPack.find(item)
      end
      @number_of_items += @pack_list.count
      # fetching single tracks
      @single_tracks_list = []
      @items.sinlge_tracks.each do |item|
        SingleTrack.find_by_id(item) ? @single_tracks_list << SingleTrack.find(item) : false
      end
      @number_of_items += @single_tracks_list.count
      @total_value = 0
      @sum = 0

      current_sales.each do |sale|
        sale.packs.each do |pack_id|
          @current_sales_list[pack_id] = sale.percentage
        end
      end

      # adding up prices of Packs depending on sales or not and usual 20% discount
      if current_sales.count > 0
        @pack_list.each do |pack|
          # calculating conversion rate
          if pack.currency_symbol != session[:currency]
            conversion_rate = CurrencyRate.where("base = ? AND target = ?", pack.currency.upcase, CurrencySymbolService.lookup(session[:currency]).upcase).order(created_at: :desc).first.rate.to_f
          else
            conversion_rate = 1
          end
          @current_sales_list[pack.id] ? @sum += ((pack.price_cents * conversion_rate) * ((100 - @current_sales_list[pack.id]) / 100.to_f)) / 100 : @sum += ((pack.price_cents * conversion_rate) / 100)
          @total_value += ((pack.price_cents * conversion_rate) / 100)
        end
      else
        @pack_list.sort_by!(&:price_cents).reverse!
        @pack_list.each_with_index do |pack, index|
          # calculating conversion rate
          if pack.currency_symbol != session[:currency]
            conversion_rate = CurrencyRate.where("base = ? AND target = ?", pack.currency.upcase, CurrencySymbolService.lookup(session[:currency]).upcase).order(created_at: :desc).first.rate.to_f
          else
            conversion_rate = 1
          end
          @total_value += ((pack.price_cents * conversion_rate) / 100)
          index.positive? ? @sum += (((pack.price_cents * conversion_rate) / 100) * 0.8) : @sum += ((pack.price_cents * conversion_rate) / 100)
        end
      end
      @total_pack_sum = @sum

      # adding up prices of single tracks
      @single_tracks_value = 0

      @single_tracks_list.each do |track|
        single_tracks = SfxPack.find(100)
        if single_tracks.currency_symbol != session[:currency]
          conversion_rate = CurrencyRate.where("base = ? AND target = ?", single_tracks.currency.upcase, "EUR").order(created_at: :desc).first.rate.to_f
        else
          conversion_rate = 1
        end
        @single_tracks_value += ((track.price_cents / 100.to_f) * conversion_rate)
        @sum += ((track.price_cents / 100.to_f) * conversion_rate)
        @total_value += ((track.price_cents / 100.to_f) * conversion_rate)
      end

      # getting the sum of points for single tracks
      @single_tracks_points = @single_tracks_list.pluck(:points).sum

      # adding up price of collection
      if @current_collections.last
        single_tracks = SfxPack.find(100)
        if single_tracks.currency_symbol != session[:currency]
          conversion_rate = CurrencyRate.where("base = ? AND target = ?", single_tracks.currency.upcase, "EUR").order(created_at: :desc).first.rate.to_f
        else
          conversion_rate = 1
        end
        @sum += ((@current_collections.last.price_cents / 100) * conversion_rate)
      end
      # this is the "You spare" part, if we do it with collections vs single tracks
      # @total_value += @current_collections.last.price_cents / 100
      @single_tracks_price = 0
      if @current_collections.last
        @current_collections.last.tracks.each { |track| @single_tracks_price += (SingleTrack.find(track).price_cents / 100.to_f) }
      end
      @total_value += @single_tracks_price
      @icons = {
        "all": '<i class="fas fa-volume-up"></i>',
        "action": '<i class="fas fa-bomb"></i>',
        "medieval": '<i class="fab fa-fort-awesome"></i>',
        "outdoor":	'<i class="fas fa-tree"></i>',
        "underground": '<i class="fas fa-dungeon"></i>',
        "scary":	'<i class="fas fa-ghost"></i>',
        "monsters":	'<i class="fas fa-dragon"></i>',
        "disasters": '<i class="fas fa-mountain"></i>',
        "weather": '<i class="fas fa-cloud-showers-heavy"></i>',
        "miscellaneous": '<i class="fas fa-volume-up"></i>',
        "footsteps": '<i class="fas fa-shoe-prints"></i>',
        "magic": '<i class="fas fa-hat-wizard"></i>',
        "scifi": '<i class="fas fa-rocket"></i>',
        "default": '<i class="fas fa-volume-up"></i>'
      }
      # @tracks = SingleTrack.where(id: [@items.sinlge_tracks]).page params[:page]
      @tracks = SingleTrack.where(id: [@items.sinlge_tracks])
    end
    @vat = VatCalculatorService.vat_amount(@sum) if @sum != nil
  end

  def delete_item
    @cart = Cart.where(user_id: current_user.id).first
    @cart.items.delete(params[:pack_id].to_i)
    if @cart.items.empty? && @cart.sinlge_tracks.empty? && @cart.collections.empty?
      @cart.destroy
    else
      @cart.save
    end
    if params[:remain] == "true"
      redirect_to root_path
    else
      redirect_to cart_path
    end
  end

  def delete_track
    cart = Cart.where(user_id: current_user.id).first
    cart.sinlge_tracks.delete(params[:id].to_i)
    if cart.items.empty? && cart.sinlge_tracks.empty? && cart.collections.empty?
      cart.destroy
    else
      cart.save
    end
    redirect_to cart_path
  end

  def single_tracks_cart_remove
    cart = Cart.where(user_id: current_user.id).first
    cart.sinlge_tracks.delete(params[:track_id].to_i)
    if cart.items.empty? && cart.sinlge_tracks.empty? && cart.collections.empty?
      cart.destroy
    else
      cart.save
    end
    if params[:page]
      redirect_to list_path(page: params[:page])
    else
      redirect_to cart_path
      #what is going on?
    end
  end

  def destroy_cart
    order = current_user.orders.last
    order.update(status: "paid")
    order.update(amount_paid_cents: order.amount_cents)
    cart = Cart.where(user_id: current_user.id).first
    if cart.collections != []
      collection = Collection.find(cart.collections.last)
      collection.purchased = true
      collection.save
    end
    cart.destroy
    redirect_to dashboard_path
  end

  private

  def collections
    @past_collections = Collection.where("user_id = #{current_user.id} AND purchased = true")
    @current_collections = Collection.where("user_id = #{current_user.id} AND purchased = false")
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/cart.html.erb
<%= render "shared/left_pannel_mobile"%>
<div class="d-flex">
  <div style="margin-top: 56px">
    <%= render "shared/left_pannel_desktop"%>
  </div>
  <% if Cart.where(user: current_user).empty? %>
    <div class="padding-navbar content cart-margins cart-font" id="cart-container">
      <h3>Your cart is empty</h3>
      <%= link_to "Go Shopping", root_path %>
    </div>
  <% else %>
    <div class="padding-navbar content cart-margins cart-font" id="cart-container">
      <div class="pannel-grid" data-controller="unwrap-cart">
        <div class="cart-pannel">
          <% if Sale.where("end_date > ?", Date.current).count > 0 %>
            <%= render 'shared/cart_sale' %>
          <% else %>
            <%= render 'shared/cart_no_sale' %>
          <% end %>
        </div>

        <!-- Checkout pannel -->
        <div class="checkout-pannel">
          <div class="total">
            <div class="container-cart-total">
              <strong><h4 style="text-align: start; margin-top: 8px">TOTAL</h4></strong>
              <hr>

              <% if @total_pack_sum != 0 %>
                <div class="d-flex justify-content-between">
                  <h6>Packs</h6>
                  <span>
                    <% if @sum.class == Float %>
                      <%= humanized_money(@total_pack_sum, symbol: session[:currency]) %>
                    <% else %>
                      <%= humanized_money(@total_pack_sum, symbol: session[:currency]) %>.00
                    <% end %>
                  </span>
                </div>
              <% end %>

              <% if @current_collections.first %>
                <% if "$" != session[:currency] %>
                  <% conversion_rate = CurrencyRate.where("base = ? AND target = ?", "USD", "EUR").order(created_at: :desc).first.rate.to_f %>
                <% else %>
                  <% conversion_rate = 1 %>
                <% end %>
                <div class="d-flex justify-content-between">
                  <h6>Collection</h6>
                  <span>
                    <% if humanized_money(@current_collections.first.price * conversion_rate) == (@current_collections.first.price * conversion_rate).to_i %>
                      <%= humanized_money(@current_collections.first.price * conversion_rate, symbol: session[:currency]) %>.00
                    <% else %>
                      <%= humanized_money(@current_collections.first.price * conversion_rate, symbol: session[:currency]) %>
                    <% end %>
                  </span>
                </div>
              <% end %>

              <% if @single_tracks_value != 0 %>
                <% if "$" != session[:currency] %>
                  <% conversion_rate = CurrencyRate.where("base = ? AND target = ?", "USD", "EUR").order(created_at: :desc).first.rate.to_f %>
                <% else %>
                  <% conversion_rate = 1 %>
                <% end %>
                <div class="d-flex justify-content-between">
                  <h6>Single-Tracks</h6>
                  <span>
                    <% if @single_tracks_value == @single_tracks_value.to_i %>
                      <%= humanized_money(@single_tracks_value, symbol: session[:currency]) %>.00
                    <% else %>
                      <%= humanized_money(@single_tracks_value, symbol: session[:currency]) %>
                    <% end %>
                  </span>
                </div>
              <% end %>

              <hr>
              <div class="d-flex justify-content-between">
                <h6>Total</h6>
                <span>
                  <% if @sum.class == Float %>
                    <%= humanized_money(@sum, symbol: session[:currency]) %>
                  <% else %>
                    <%= humanized_money(@sum, symbol: session[:currency]) %>.00
                  <% end %>
                </span>
              </div>
              <div class="d-flex justify-content-between cart-vat-display">
                <span>VAT (19% inclusive)</span>
                <span>
                  <% if @vat.class == Float %>
                    <%= humanized_money(@vat, symbol: session[:currency]) %>
                  <% else %>
                    <%= humanized_money(@vat, symbol: session[:currency]) %>,00
                  <% end %>
                </span>
              </div>
              <% if (@total_value - @sum) > 0 %>
                <p style="text-align: end; font-size: 0.8em; font-style: italic">(You spare <%= humanized_money(@total_value - @sum, symbol: session[:currency]) %>)</p>
              <% else %>
                <div style="height: 10px;"></div>
              <% end %>
              <div class="d-flex justify-content-between">
                <div id="continue-shopping">
                  <%= link_to "Continue shopping", root_path %>
                </div>
                <div>
                  <%= form_tag checkout_path(cart_id: @items.id, collection_id: @current_collections.first, currency: session[:currency]) do %>
                    <%= submit_tag 'Checkout', id: 'btn-cart' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>